import rospy
from clover import srv
from std_srvs.srv import Trigger
rospy.init_node('flight')

get_telemetry = rospy.ServiceProxy('get_telemetry', srv.GetTelemetry)
navigate = rospy.ServiceProxy('navigate', srv.Navigate)
navigate_global = rospy.ServiceProxy('navigate_global', srv.NavigateGlobal)
set_altitude = rospy.ServiceProxy('set_altitude', srv.SetAltitude)
set_yaw = rospy.ServiceProxy('set_yaw', srv.SetYaw)
set_yaw_rate = rospy.ServiceProxy('set_yaw_rate', srv.SetYawRate)
set_position = rospy.ServiceProxy('set_position', srv.SetPosition)
set_velocity = rospy.ServiceProxy('set_velocity', srv.SetVelocity)
set_attitude = rospy.ServiceProxy('set_attitude', srv.SetAttitude)
set_rates = rospy.ServiceProxy('set_rates', srv.SetRates)
land = rospy.ServiceProxy('land', Trigger)

navigate(x=0, y=0, z=1.5, speed=0.5, frame_id='body', auto_arm=True)
rospy.sleep(5)
navigate(frame_id='aruco_148', x=0, y=0, z=1)
rospy.sleep(5)
navigate(frame_id='aruco_155', x=0, y=0, z=1)
rospy.sleep(5)
navigate(frame_id='aruco_145', x=0, y=0, z=1)
rospy.sleep(5)
navigate(frame_id='aruco_157', x=0, y=0, z=1)
rospy.sleep(5)
navigate(frame_id='aruco_146', x=0, y=0, z=1)
rospy.sleep(5)
navigate(frame_id='aruco_147', x=0, y=0, z=1)
rospy.sleep(5)
navigate(frame_id='aruco_144', x=0, y=0, z=1)
rospy.sleep(5)
navigate(frame_id='aruco_143', x=0, y=0, z=1)
rospy.sleep(5)
navigate(frame_id='aruco_159', x=0, y=0, z=1)
rospy.sleep(5)
navigate(frame_id='aruco_158', x=0, y=0, z=1)
rospy.sleep(5)
navigate(frame_id='aruco_156', x=0, y=0, z=1)
rospy.sleep(5)
navigate(frame_id='aruco_160', x=0, y=0, z=1)
rospy.sleep(5)
land()
